### PR TITLE
Markdup preseq

### LINKED ISSUE #1: Add PRESEQ module (and dependencies) for complexity Analysis
I've a microbiome sample that I need to estimate how much deeper to sequence.

This can be extrapolated via preseq analysis of deduplicated BAM files, and in the case of microbiome samples across multiple species.

I would like to add optional deduplication and preseq processes to allow me to get this information.

Edit: blocked from assigning myself, but assume I'll do this

### PR DESCRIPTION
**Pull request by jfy133**
This closes #1 

Outsanding things:

1. Bug - markduplicates in MultiQC splits everything after `.`, and an sam2lca keeps the `.sorted` part of the output of an earlier `samtools sort`, but this means we don't have the taxid indicating which BAM is which resulting in MuiltiQC only reporting a random entry for each SAMPLE (as each taxid is overwritten) 
2. Question - do you want the deduplicated BAM going into downstream steps (freebayes, damageprofiler etc.)

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by maxibor** [comment]
Failing. Apparently markduplicates only accepts sorted files.
You should use the output of the `BAM_SORT_SAMTOOLS` subworkflow.
Also, I think it would be better to make markduplicate a subworkflow (here or part of the nf-core subworkflows) ? This way, it's makes it easyer to only conditioanally execute it.

**Comment by jfy133** [comment]
Hm ,apparetly  I can't request reviewer at the top right - sorry will have to ping here @maxibor

**Comment by maxibor** [comment]
Hmm :(
```bash
[5b/e3f6ed] Submitted process > ADNAMAP:PRESEQ_LCEXTRAP (SAMPLE3)
[5b/e3f6ed] NOTE: Process `ADNAMAP:PRESEQ_LCEXTRAP (SAMPLE3)` terminated with an error exit status (1) -- Error is ignored
```

**Comment by jfy133** [comment]
> Hmm :(
> 
> ```shell
> [5b/e3f6ed] Submitted process > ADNAMAP:PRESEQ_LCEXTRAP (SAMPLE3)
> [5b/e3f6ed] NOTE: Process `ADNAMAP:PRESEQ_LCEXTRAP (SAMPLE3)` terminated with an error exit status (1) -- Error is ignored
> ```

Nope, that's to be expected, doesn't have sufficient depth - all good! some of them do work successfully :)

**Pull request merged**
